### ISSUE TITLE
Contigs binning -marker genes/hmmout problem

### ISSUE THREAD

**Issue by Nafson194** [anuradhawick/LRBinner#19]
Hi @anuradhawick,

I am running LRBinner for ONT contigs generated from metaFlye. I would like to bin the contigs and come across this tool for binning of long reads data, however, I am running in the error  indicating a missing file.

Could please give a helping hand on how to solve the problem?

Best,
Nafi'u

here is the command I ran and error produced
command:
/tools/LRBinner/lrbinner.py contigs --reads-path Porechop/sample01.fastq   --contigs final_assembly/sample01.assembly.fasta  --output binning/

2024-02-27 14:29:48,189 - INFO - Computing contig lengths
2024-02-27 14:29:48,245 - INFO - Searching for marker genes 
Traceback (most recent call last):
  File "/lustre/groups/comi/tools/LRBinner/lrbinner.py", line 203, in <module>
    main()
  File "/lustre/groups/comi/tools/LRBinner/lrbinner.py", line 185, in main
    pipelines.run_contig_binning(args)
  File "/lustre/groups/comi/tools/LRBinner/mbcclr_utils/pipelines.py", line 79, in run_contig_binning
    marker_gene_utils.get_contigs_with_marker_genes(output, 0.5, contig_length, 1000)
  File "/lustre/groups/comi/tools/LRBinner/metacoag_utils/marker_gene_utils.py", line 55, in get_contigs_with_marker_genes
    with open(f"{output}/marker_genes/contigs.hmmout", "r") as myfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: '07_binning/marker_genes/contigs.hmmout'

**Comment by anuradhawick** [comment]
Hi thanks for getting in touch.  

Could you check if these are available in your system?

- fraggenescan 1.31
- hmmer 3.3.2

**Comment by Nafson194** [comment]
Hi @anuradhawick ,

Thank you for getting back to me.

I managed to run it successfully after installing the tool using conda. However, I have one more issues that I would like to clarify with you. I used metabat2 for binning of one sample and generated 7 bins. Later, this tool started running and produced only two bins from the same sample. Do you know any reason behind generating few bins compared to the software not designed purposely for binning of long reads sequences?

Best,
Nafi'u

**Comment by anuradhawick** [comment]
I think LRBinner can give lesser number of bins for assemblies because I have not designed it for binning contigs. 

On the other hand, contigs binning tools may have heuristics more applicable for contigs like accuracy. If it's using marker genes long reads might mislead the binner too.

**Comment by Nafson194** [comment]
Thank you for the information. May I know if you know/have any other tool for binning of assemblies from long reads?

Maybe tools designed specifically for long reads binning would give a better genomes in terms of quality.

Thanks

**Comment by anuradhawick** [comment]
You could try this

https://github.com/metagentools/MetaCoAG

**Comment by Nafson194** [comment]
Thank you for your response and recommendation.
